
networks:
  cloud-vpc:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16

services:
  # --- Identity Provider (AuthN & RBAC) ---
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: vault_idp
    command: start-dev
    environment:
      # Interpolated from .env!
      KEYCLOAK_ADMIN: ${INFRA_KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${INFRA_KEYCLOAK_PASSWORD}
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak-theme/vault-theme:/opt/keycloak/themes/vault-theme
    networks:
      cloud-vpc:
        ipv4_address: 10.5.0.40

  # 1. Cloud DNS (Route 53)
  internal-dns:
    image: coredns/coredns:latest
    container_name: vault_dns
    command: -conf /etc/coredns/Corefile
    volumes:
      - ./dns:/etc/coredns
    networks:
      cloud-vpc:
        ipv4_address: 10.5.0.53

  # 2. Object Storage (S3)
  minio:
    image: minio/minio:latest
    container_name: local-s3-engine
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      # Interpolated from .env!
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: server /data --console-address ":9001"
    networks:
      cloud-vpc:
        ipv4_address: 10.5.0.10

  # 3. FastAPI Web Application
  api-service:
    build: .
    container_name: vault_api
    ports:
      - "8000:8000"
    dns:
      - 10.5.0.53  # Forces the API to ask CoreDNS for directions!
    env_file:
      - .env       # Loads the unified vault.local endpoint
    depends_on:
      - internal-dns
      - minio
      - keycloak
    networks:
      cloud-vpc:


# 4. Frontend Application
  webapp:
    build: ./frontend
    container_name: vault_ui
    ports:
      - "3000:3000"
    depends_on:
      - api-service
    networks:
      cloud-vpc:
        ipv4_address: 10.5.0.20

volumes:
  minio_data:
